baseURL = 'https://theorestes.github.io/'
languageCode = 'en-us'
title = "The Pixel Dump"
theme = "enervoid-theme"

[menus]
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 10

  [[menus.main]]
    name = 'Personal'
    pageRef = '/personal'
    weight = 20

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 30

[params]
  avatar = "/images/website_icon.jpg"

  [[params.socials]]
      link = "https://github.com/TheOrestes"
      icon = "devicon-github-original"
  [[params.socials]]
      link = "https://x.com/rupeshmandke"
      icon = "devicon-twitter-original"
   [[params.socials]]
      link = "https://www.linkedin.com/in/rupesh-mandke-27a7234"
      icon = "devicon-linkedin-plain"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['$$','$$'], ['\\[','\\]']]
        inline = [['$','$'], ['\\(','\\)']]

    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[markup.highlight]
  noClasses = true
  codeFences = true
  guessSyntax = true
  tabWidth = 4
  style = "monokai"